const lootData = {
    gold: {
        contents: 'gold',
        description: 'A pile of golden coins',
        value: 10,
        weight: 10,
        strength: 0,
        creature: false,
        treasure: true,
        friendly: false,
        hostile: false,
        friendChance: 0,
        hostileChance: 0,
        attack: 0,
        magic: 0,
        imageSrc: 'gfx/dungeon-crawl-stone-soup-edited/gold_pile_10.png',
        widthFrame: 32, heightFrame: 32,
        stillImage: {x: 0, y: 0},
        scale: .5,
    },
    gems: {
        contents: 'gems',
        description: 'Many beautiful precious gems.',
        value: 25,
        weight: 5,
        strength: 0,
        creature: false,
        treasure: true,
        friendly: false,
        hostile: false,
        friendChance: 0,
        hostileChance: 0,
        attack: 0,
        magic: 0,
        imageSrc: 'gfx/dungeon-crawl-stone-soup-edited/misc_crystal_old.png',
        widthFrame: 32, heightFrame: 32,
        stillImage: {x: 0, y: 0},
        scale: .5,
    },
    man: {
        contents: 'man',
        description: 'A human man, slightly pale from his time in the cave.',
        value: 5,
        weight: 0,
        strength: 50,
        creature: true,
        treasure: false,
        friendly: false,
        hostile: false,
        friendChance: 8,
        neutralChance: 0,
        hostileChance: 2,
        friendRoll: {max: 6, min: 4},
        neutralRoll: {max: 3, min: 2},
        hostileRoll: {max: 1, min: 1},
        attack: 3,
        magic: 0,
        imageSrc: 'gfx/creatures/man.png',
        northFrameOffset: 0, westFrameOffset: 1, southFrameOffset: 2, eastFrameOffset: 3,
        widthFrame: 64, heightFrame: 64,
        stillImage: {x: 0, y: 640},
        walkFrames: {x: 0, y: 512, length: 8},
        attackFrames: {x: 0, y: 768, length: 6},
        deathFrames: {x: 0, y: 1344, length: 6},
    },
    heroine: {
        contents: 'heroine',
        description: 'A human woman, made heroic by circumstance and ability.',
        value: 10,
        weight: 0,
        strength: 50,
        creature: true,
        treasure: false,
        friendly: false,
        hostile: false,
        friendRoll: {max: 6, min: 5},
        neutralRoll: {max: 4, min: 2},
        hostileRoll: {max: 1, min: 1},
        attack: 4,
        magic: 0,
        imageSrc: 'gfx/creatures/heroine.png',
        northFrameOffset: 0, westFrameOffset: 1, southFrameOffset: 2, eastFrameOffset: 3,
        widthFrame: 64, heightFrame: 64,
        stillImage: {x: 0, y: 640},
        walkFrames: {x: 0, y: 512, length: 8},
        attackFrames: {x: 0, y: 768, length: 6},
        deathFrames: {x: 0, y: 1344, length: 6},
    },
    giant: {
        contents: 'giant',
        description: 'Very tall and strong.',
        value: 5,
        weight: 0,
        strength: 175,
        creature: true,
        treasure: false,
        friendly: false,
        hostile: false,
        friendChance: 5,
        neutralChance: 3,
        hostileChance: 2,
        friendRoll: {max: 6, min: 6},
        neutralRoll: {max: 5, min: 3},
        hostileRoll: {max: 2, min: 1},
        attack: 4,
        magic: 0,
        imageSrc: 'gfx/creatures/giant.png',
        northFrameOffset: 0, westFrameOffset: 1, southFrameOffset: 2, eastFrameOffset: 3,
        widthFrame: 64, heightFrame: 64,
        stillImage: {x: 0, y: 640},
        walkFrames: {x: 0, y: 512, length: 8},
        attackFrames: {x: 0, y: 768, length: 6},
        deathFrames: {x: 0, y: 1344, length: 6},
        scale: 1.25,
    },
    priest: {
        contents: 'priest',
        description: 'A devotee of a divine being',
        value: 5,
        weight: 0,
        strength: 25,
        creature: true,
        treasure: false,
        friendly: false,
        hostile: false,
        friendChance: 7,
        neutralChance: 1,
        hostileChance: 2,
        friendRoll: {max: 6, min: 5},
        neutralRoll: {max: 4, min: 3},
        hostileRoll: {max: 2, min: 1},
        attack: 2,
        magic: 2,
        imageSrc: 'gfx/creatures/priest.png',
        northFrameOffset: 0, westFrameOffset: 1, southFrameOffset: 2, eastFrameOffset: 3,
        widthFrame: 64, heightFrame: 64,
        stillImage: {x: 0, y: 640},
        walkFrames: {x: 0, y: 512, length: 8},
        attackFrames: {x: 0, y: 768, length: 6},
        deathFrames: {x: 0, y: 1344, length: 6},
    },
    wizard: {
        contents: 'wizard',
        description: 'An expert in the arcane arts',
        value: 5,
        weight: 0,
        strength: 25,
        creature: true,
        treasure: false,
        friendly: false,
        hostile: false,
        friendChance: 2,
        neutralChance: 2,
        hostileChance: 6,
        friendRoll: {max: 6, min: 6},
        neutralRoll: {max: 5, min: 4},
        hostileRoll: {max: 3, min: 1},
        attack: 2,
        magic: 5,
        imageSrc: 'gfx/creatures/wizard.png',
        northFrameOffset: 0, westFrameOffset: 1, southFrameOffset: 2, eastFrameOffset: 3,
        widthFrame: 64, heightFrame: 64,
        stillImage: {x: 0, y: 640},
        walkFrames: {x: 0, y: 512, length: 8},
        attackFrames: {x: 0, y: 768, length: 6},
        deathFrames: {x: 0, y: 1344, length: 6},
    },
    sorcerer: {
        contents: 'sorcerer',
        description: 'Ruler of the cave, very angry that you are stealing from them!',
        value: 0,
        weight: 0,
        strength: 0,
        creature: true,
        treasure: false,
        friendly: false,
        hostile: false,
        friendChance: 0,
        neutralChance: 0,
        hostileChance: 10,
        friendRoll: {max: 0, min: 0},
        neutralRoll: {max: 0, min: 0},
        hostileRoll: {max: 6, min: 1},
        attack: 2,
        magic: 11,
        imageSrc: 'gfx/creatures/sorcerer.png',
        northFrameOffset: 0, westFrameOffset: 1, southFrameOffset: 2, eastFrameOffset: 3,
        widthFrame: 64, heightFrame: 64,
        stillImage: {x: 0, y: 640},
        walkFrames: {x: 0, y: 512, length: 8},
        attackFrames: {x: 0, y: 768, length: 6},
        deathFrames: {x: 0, y: 1344, length: 6},
    },
    specter: {
        contents: 'specter',
        description: 'An undead ghost or revenant',
        value: 0,
        weight: 0,
        strength: 0,
        creature: true,
        treasure: false,
        friendly: false,
        hostile: false,
        friendChance: 0,
        neutralChance: 0,
        hostileChance: 10,
        friendRoll: {max: 0, min: 0},
        neutralRoll: {max: 0, min: 0},
        hostileRoll: {max: 6, min: 1},
        attack: 0,
        magic: 7,
        imageSrc: 'gfx/Grue/GrueBloodyRearranged.png',
        northFrameOffset: 0, westFrameOffset: 1, southFrameOffset: 2, eastFrameOffset: 3,
        widthFrame: 56, heightFrame: 71,
        stillImage: {x: 0, y: 142},
        walkFrames: {x: 0, y: 0, length: 1},
        scale: .65,
    },
}
let lootDeck = [
    lootData.gold, lootData.gold, lootData.gems,
    lootData.man, lootData.priest, lootData.wizard, lootData.specter,
    lootData.sorcerer, lootData.giant
];

module.exports = {
    lootData,
    lootDeck,
};
